# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# 添加模块所在路径
flutter_application_path = 'my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'StyfStudyNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'SDWebImage'
  pod 'Masonry'
  pod 'AFNetworking'
  
  # 安装Flutter模块
  install_all_flutter_pods(flutter_application_path)
  
  pod 'GLResponderChain', '~> 1.0.3'
#  pod 'Animatable', '~> 1.0.6'
end
