# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StyfStudyNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'SDWebImage'
  pod 'Masonry'
  pod 'AFNetworking'
  
  
  pod 'GLResponderChain', '~> 1.0.3'
#  pod 'Animatable', '~> 1.0.6'
end
