excluded:
  - DerivedData

disabled_rules:
  - orphaned_doc_comment
  - comment_spacing

force_cast: warning # 1

identifier_name: # 2
  excluded:
    - i
    - id
    - x
    - y
    - z

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
    warning: 70

opt_in_rules:
  - indentation_width
  - force_unwrapping
  - redundant_type_annotation
  - force_try
  - operator_usage_whitespace

indentation_width:
  indentation_width: 2
